### ISSUE TITLE
Idea: custom function which displays results of all inputs in a dialog

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/BZS-FuncLib#141]
So, if your dialog is:

![image](https://cloud.githubusercontent.com/assets/5701751/10826899/ee4c4d10-7e39-11e5-899f-bf78bb03df8f.png)

Then it creates a MsgBox, like so:

![image](https://cloud.githubusercontent.com/assets/5701751/10827407/cac6ef14-7e3c-11e5-9411-0647827d07f0.png)

I figure this could be useful for debugging, user confirmation, etc. I'm thinking we can do it with arrays. Any thoughts/takers?

**Comment by theVKC** [comment]
Also, thinking this might be fun with dynamic dialogs. Classes maybe?

**Comment by theVKC** [comment]
@MN-Script-Team/functions-library-contributors, any thoughts on this? Feedback is needed, folks!

**Comment by lpshanley** [comment]
Dialog or text field?

-Lucas
“Valar dohaeris”
#DecimateTheErrorRate
P Please consider the environment before printing this email. P

**Comment by theVKC** [comment]
I'm thinking a MsgBox.

**Comment by Y-Lor-Y** [comment]
My thought on this:
1) We already have safety loop build into some area - how will these be impacted?
2) I can see where this is heading with the changes coming to the CAF script and chaining scripts, this might be a great idea for that.
3) double check input values and decrease error(s)

It'll be great for stand alone dialogs that are simple or common or short, but might be 'time' consuming for bigger scripts.  I don't want this to shy people away from not buying into the idea or not using scripts because it's time consuming works.  You may get more buy-in from smaller counties with lower caseload, but you may not from a higher caseload worker.  Just my two cents.

**Comment by theVKC** [comment]
My thought would be it would be far more valuable to scriptwriters than script users. It's a good thing for developer modes and testing.

**Comment by CDPotter** [comment]
Oh I was thinking it would be moreso for end users rather than script writers using this. If it was to be employed on end users I think it would HAVE to be optional(checkbox to display preview). As for replacing manually coding developer mode. I don't think it's that needed. I like having the control over what displays for my developer mode.

**Comment by IlseFerris** [comment]
I see value in both. Especially for users when using action scripts, and other complicated scripts.

**Comment by theVKC** [comment]
I get sick of trying to figure out what's in my variables when debugging. This goes hand-in-hand with developer mode, in my opinion. But, the underlying code could also be used for "are you sure" type dialogs, hence why I like it.

**Comment by lpshanley** [comment]
I think this has a nice array of uses and in addition to what has already been stated, I apologize is this was previously stated, but if programmed correctly these could be layered into an array or object in some form so that when you chain once script to another similar variables could carry over from script to script while its being run in the same instance so that it would even cut down on the amount of duplicate work that users are doing! I say that it’s a good idea ☺

-Lucas
“Valar dohaeris”
#DecimateTheErrorRate
P Please consider the environment before printing this email. P

**Comment by theVKC** [comment]
Even a function to create a MsgBox out of a two-dimensional array (displaying both columns) could be a good start. :)

**Comment by C-Love** [comment]
I think it would be helpful with script writing. 

But it would also be beneficial as a double check for those scripts that have small but vital dialogs to kick things off - like the CAF script (as it exists now and in the Gorbochov form) where having the right case number and footer month is pretty vital. It gives the workers a chance to double check it.

**Comment by theVKC** [comment]
I'm taking it. Thanks for the feedback all. :)

I'm going to start with a simple function that can generate a MsgBox based on an array. We'll expand from there.

**Comment by theVKC** [comment]
I haven't had time for this. I'll mark it as help wanted for now, if nobody wants it at hackathon next Monday I'll close it.
