### ISSUE TITLE
Is end_excel_and_script really needed anymore?

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/BZS-FuncLib#337]
It's still there. And it's not documented. Thinking I might dispose of it.

@C-Love? @IlseFerris? @CDPotter? @RoberT-1000?

**Comment by RoberT-1000** [comment]
Anoka will be OK without it.

**Comment by IlseFerris** [comment]
Hennepin is good without it as well.

**Comment by CDPotter** [comment]
I'm looking at it being used in CSES scrubber.

**Comment by theVKC** [comment]
But should it? CSES scrubber should leave the Excel open on close now, right?

**Comment by CDPotter** [comment]
Looks like its used when case note isn't in production. 

![image](https://cloud.githubusercontent.com/assets/7841989/21153502/56dee83a-c130-11e6-875b-662b3f85820e.png)

Since it's not invisible anymore we could probably just change it to one script end procedure and trust people to close their open excel window on their own. 

I'm racking by brain trying to think of any other invisible excel files we use... maybe they were all just local Anoka ones at some point that I'm thinking of.

**Comment by theVKC** [comment]
Because @CDPotter has left and MAXIS is unsupported, I'm closing this issue.
